config/routes.rb
Rails.application.routes.draw do
  resources :libros
  resources :autors
  root :to => "libros#index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base
	has_many :libros
end

app/models/libro.rb
class Libro < ActiveRecord::Base
  belongs_to :autor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: [:show, :edit, :update, :destroy]

  # GET /autors
  # GET /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1
  # GET /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors
  # POST /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: 'Autor was successfully created.' }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1
  # PATCH/PUT /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: 'Autor was successfully updated.' }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.json
  def destroy
    @autor.destroy
    respond_to do |format|
      format.html { redirect_to autors_url, notice: 'Autor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autor_params
      params.require(:autor).permit(:nombre, :apellidos)
    end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/autors/_form.html.erb
<%= form_for(@autor) do |f| %>
  <% if @autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
      <% @autor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing Autor</h1>

<%= render 'form' %>

<%= link_to 'Show', @autor %> |
<%= link_to 'Back', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>

<font size=100 color="red">Lista de Autores</font>
<%= simple_format("\n") %>

<table cellspacing="15" cellpading = "10">
  <thead>
    <tr>
      <th><h2>Id<h2></th>
      <th><h2>Nombre<h2></th>
      <th><h2>Apellidos<h2></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><font color="blue"><%= autor.id %></font></td>
        <td><font color="blue"><%= autor.nombre %></font></td>
        <td><font color="blue"><%= autor.apellidos %></font></td>
        <td><%= link_to 'Mostrar', autor %></td>
        <td><%= link_to 'Editar', edit_autor_path(autor) %></td>
        <td><%= link_to 'Borrar', autor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo autor', new_autor_path %>
<%= link_to 'Lista Libros', libros_path %>

app/views/autors/new.html.erb
<h1>New Autor</h1>

<%= render 'form' %>

<%= link_to 'Back', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @autor.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @autor.apellidos %>
</p>

<%= link_to 'Edit', edit_autor_path(@autor) %> |
<%= link_to 'Back', autors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
    <%= yield %>
  </div>

</body>
</html>

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor_id %><br>
    <%= f.text_field :autor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<font size=100 color="red">Lista de Libros</font>

<table cellspacing="15" cellpading = "10">
  <thead>
    <tr>
      <th><h2>Titulo<h2></th>
      <th><h2>Autor<h2></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><font color="blue"><%= libro.titulo + " "%></font></td>
        <% if libro.autor != nil%>
          <td><font color=blue><%= libro.autor.nombre + " " + libro.autor.apellidos %></font></td>
        <% else %>
          <td><%= "Autor Desconocido" %></td>
        <% end %>
        <td><%= link_to 'Mostrar', libro %></td>
        <td><%= link_to 'Editar', edit_libro_path(libro) %></td>
        <td><%= link_to 'Borrar', libro, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
    <%= simple_format("\n") %>
  </tbody>
</table>

<br>

<strong><%= link_to 'Nuevo libro', new_libro_path %></strong>
<%= link_to 'Lista Autores', autors_path %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @libro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.autor %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>